ALTER TABLE sellers
ADD COLUMN contact_person VARCHAR(150),
ADD COLUMN email VARCHAR(255),
ADD COLUMN phone VARCHAR(20),
ADD COLUMN address TEXT,
ADD COLUMN city VARCHAR(100),
ADD COLUMN state VARCHAR(100),
ADD COLUMN pincode VARCHAR(10),
ADD COLUMN gstin VARCHAR(20),
ADD COLUMN business_type VARCHAR(100);