spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bajrix
spring.datasource.username=bajrix
spring.datasource.password=bajrix123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

server.port=8080